[tool.poetry]
name = "bacalhau"
version = "0"
description = ""
authors = []

[tool.poetry.dependencies]
python = "^3.9"
pre-commit = "^2.20.0"
sgqlc = "^16.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
