title: Ops Bacalhau Dependency
scms:
  default:
    kind: "github"
    spec:
      owner: "filecoin-project"
      repository: "bacalhau"
      username: philwinder
      token: "{{ requiredEnv `UPDATECLI_GHP` }}"
      branch: "main"
sources:
  default:
    kind: githubrelease
    spec:
      owner: "filecoin-project"
      repository: "bacalhau"
      username: philwinder
      token: "{{ requiredEnv `UPDATECLI_GHP` }}"
      versionFilter:
        kind: latest
pullrequests:
  default:
    kind: "github"
    scmid: "default"
    spec:
      description: 'Bump ops clusters to "{{ source `default` }}". This is an automated PR.'
      draft: false
      labels:
        - "dependencies"
      title: 'chore(ops): update Bacalhau clusters to "{{ source `default` }}"'
targets:
  development:
    name: Bump Dev
    kind: file
    scmid: default
    spec:
      file: ops/terraform/development.tfvars
      line: 1
      content: bacalhau_version       = "{{ source `default` }}"
  staging:
    name: Bump Staging
    kind: file
    scmid: default
    spec:
      file: ops/terraform/staging.tfvars
      line: 1
      content: bacalhau_version       = "{{ source `default` }}"
  production:
    name: Bump Prod
    kind: file
    scmid: default
    spec:
      file: ops/terraform/production.tfvars
      line: 1
      content: bacalhau_version           = "{{ source `default` }}"
