Node:
  Type:
    - compute
  ClientAPI:
    Host: ${requester_ip}
    Port: 443
    ClientTLS:
      UseTLS: true
      CaCert: /bacalhau_repo/bacalhau_cert.crt
  BootstrapAddresses:
  Network:
    Type: nats
    Port: 4222
    AuthSecret: ${compute_api_token}
    Orchestrators:
      - nats://${compute_api_token}@${requester_ip}:4222
    Cluster:
      Name: global
      Port: 6222
  Compute:
    JobSelection:
      Locality: anywhere
      AcceptNetworkedJobs: ${bacalhau_accept_networked_jobs}
  AllowListedLocalPaths:
    - "/bacalhau_local_data/**"
  UpdateConfig:
    SkipChecks: true