name: TestContainers Suite

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      arch:
        required: true
        type: string

jobs:
  test-build-and-run-testcontainers:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download compiled binary
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.os }}-${{ inputs.arch }}
          path: compiled-artifacts/

      - name: Install Golang
        uses: actions/setup-go@v5
        with:
          go-version-file: go.work

      - name: Run Go tests in integration test directory
        shell: bash
        run: |
          echo "===> Copy compiled artifact to use in docker images..."
          cd compiled-artifacts
          tar -xzf bacalhau_*.tar.gz
          cp ./bacalhau ../test_integration/common_assets/bacalhau_bin
          
          echo "===> Running tests..."       
          cd ../test_integration
          go test -v -count=1 ./...
